CREATE TABLE gl_hydy
(
  hydm character varying(20),
  gh character varying(20),
  xm character varying(40),
  xb character varying(1),
  jgdm integer,
  sr character varying(10),
  mm character varying(10),
  zt character varying(1),
  dlcs integer,
  jsdm character varying(4),
  kzjs character varying(100),
  profile character varying(20),
  kzpz character varying(20),
  zxsj character varying(20),
  ztgxsj character varying(20),
  dwdh character varying(20),
  dwcz character varying(20),
  sj character varying(20),
  xlt character varying(20),
  glqx character varying(1),
  zdglqx_id character varying(100),
  zdglqx_mc character varying(100),
  bz character varying(200),
  onlinestate character varying(1),
  sfcykp character varying(1),
  sskpjg_id character varying(1000),
  sskpjg_mc character varying(1000),
  jbdm integer,
  gwdm integer,
  sfbhzbm character varying(1),
  fj character varying(500),
  cxgyh character varying(12),
  dggyh character varying(12),
  CONSTRAINT gl_hydy_idx UNIQUE (hydm)
)